### PR TITLE
Fix UI bugs, connect discover to redux, and add loading notifications

### LINKED ISSUE #134: Show loading indicator when library is first being loaded
When a user first logs in, it loads the library async. Right now the library screen will show empty library view until the request finishes.

We could show a spinner while this loading takes place to show the user the data is still being fetched.

This can be done by checking if `librarydecks` is `null`. This means the decks hasn't been loaded yet.

### LINKED ISSUE #136: Card counter in DeckThumbnail is wrong until the deck is synced
If a deck is created locally, then the counter displays "undefined cards" until the deck is synced.

screen shot 2017-03-21 at 6 16 02 am

If the deck is updated locally, the counter does not update until the deck is synced.

`DeckThumbnail` now pulls the number of cards from the `num_cards` property, which is not created in the `createDeck` action and is not updated by the `editDeck` reducer. This was originally intended so that the number of cards could still be displayed even when we only had a deck's metadata (in Discover and Search), but we should consider only using `num_cards` as a fallback in case the `cards` property is not present.

### PR DESCRIPTION
**Pull request by henryc132**
Closes #136 
Closes #134 

Fixes:
- Fix card counter on thumbnail for newly created decks
- Fix background color on DeckPreview page.
- Connected DiscoverHome to the redux store.
- Added swipe to refresh on DiscoverHome
- Show spinner while Library or Discover page is loaded for first time

### CODE REVIEW

File: Cue/app/tabs/library/LibraryHome.js [hunk 1]
```diff
@@ -66,10 +66,12 @@ class LibraryHome extends React.Component {
...
   constructor(props: Props) {
     super(props)
-
+
+    let refreshing = this.props.decks ? false : true;
+
     this.state = {
       editing: false,
-      refreshing: false,
+      refreshing: refreshing,
```
Comment (mattyu007) [inline Cue/app/tabs/library/LibraryHome.js]: You don't need to write `refreshing: refreshing`, you can just write `refreshing`.

File: Cue/app/store/configureStore.js [hunk 2]
```diff
@@ -20,8 +20,8 @@ var createCueStore = applyMiddleware(thunk, promise, logger)(createStore);
 
 function configureStore(onComplete: ?() => void) {
   const store = autoRehydrate()(createCueStore)(reducers);
-  persistStore(store, {storage: AsyncStorage, blacklist: ['tabs', 'discover']}, onComplete);
-  
+  persistStore(store, {storage: AsyncStorage, blacklist: ['tabs']}, onComplete);
```
Comment (mattyu007) [inline Cue/app/store/configureStore.js]: Do we want search results and the Discover page to persist across sessions?

File: Cue/app/tabs/discover/DiscoverHome.js [hunk 3]
```diff
@@ -25,37 +28,61 @@ const styles = {
 
 type Props = {
   navigator: Navigator,
-  onPressMenu?: () => void
+  onPressMenu?: () => void,
+
+  newDecks: ?Array<DeckMetadata>,
+  topDecks: ?Array<DeckMetadata>,
+  onDiscover: () => any,
```
Comment (mattyu007) [inline Cue/app/tabs/discover/DiscoverHome.js]: `onRefreshDiscover`?

File: Cue/app/tabs/discover/DiscoverHome.js [hunk 4]
```diff
@@ -25,37 +28,61 @@ const styles = {
...
 }
 
 class DiscoverHome extends React.Component {
   props: Props
 
   state: {
-    dataSource: ListView.DataSource
+    dataSource: ListView.DataSource,
+    loading: boolean,
```
Comment (mattyu007) [inline Cue/app/tabs/discover/DiscoverHome.js]: `loading` is not used?

**Review by mattyu007 — COMMENTED** [review]
Looks good, just a few minor things.

It was so hard to verify that the loading spinner actually came up for the Library and Discover home pages since the loading time is so short, but indeed they do show up if I use a network link conditioner to simulate a 2G connection 😝

**Comment by henryc132** [comment]
@mattyu007 werent you going to sleep? lol

File: Cue/app/tabs/discover/DiscoverHome.js (hunk 4 above)
Comment (henryc132) [reply Cue/app/tabs/discover/DiscoverHome.js]: Yea, forgot to remove it

File: Cue/app/store/configureStore.js (hunk 2 above)
Comment (henryc132) [reply Cue/app/store/configureStore.js]: Yea, it wouldn't make sense to show really old data

File: Cue/app/tabs/discover/DiscoverHome.js [hunk 5]
```diff
@@ -25,37 +28,60 @@ const styles = {
...
+
+  componentWillReceiveProps(newProps) {
+    this.setState(this._getNewState(newProps))
+  }
+
+  _refresh = () => {
+    this.setState({
+      refreshing: true
+    })
+    this.props.onRefreshDiscover()
```
Comment (Tyler-Brenneman) [inline Cue/app/tabs/discover/DiscoverHome.js]: Should add a catch here and display an alert or something that there is no internet connection

**Review by Tyler-Brenneman — COMMENTED** [review]
Should handle user not having internet connection.

Same change should probably be made to search screen as well

File: Cue/app/tabs/library/LibraryHome.js [hunk 6]
```diff
@@ -66,16 +66,18 @@ class LibraryHome extends React.Component {
 
   constructor(props: Props) {
     super(props)
-
+
+    let refreshing = this.props.decks ? false : true;
```
Comment (Tyler-Brenneman) [inline Cue/app/tabs/library/LibraryHome.js]: setting `refreshing` here will cause it to stay `true` on login. Need a way to set it to `false` once the initial `loadLibrary` after login is done.

Comment (henryc132) [reply Cue/app/tabs/library/LibraryHome.js]: weird, I swore there used to be a componentWillReceiveProps function in library home

Comment (Tyler-Brenneman) [reply Cue/app/tabs/library/LibraryHome.js]: Oh, I removed it since a `syncDeck` action would trigger it and stop the refreshing icon before `loadLibrary` was finished

Comment (henryc132) [reply Cue/app/tabs/library/LibraryHome.js]: But doesnt sync deck always happen before loadLibrary

File: Cue/app/tabs/library/LibraryHome.js [hunk 7]
```diff
@@ -65,17 +65,26 @@ class LibraryHome extends React.Component {
...
-
-  _refresh = () => {
+    super(props)
+
+    let refreshing = false
+
+    if (!this.props.deck) {
+      refreshing = true
+      this.props.onLoadLibrary().then(response => {
+        this.setState({refreshing: false})
```
Comment (henryc132) [inline Cue/app/tabs/library/LibraryHome.js:75]: Wonder what the probability of this being ran before we set state below is.

**Review by Tyler-Brenneman — APPROVED** [review]
