### PR TITLE
Fix empty public decks message

### LINKED ISSUE #123: "Add a card by tapping the + button" appears for empty decks in Preview Public Deck
We should not display the next step suggestion message for decks viewed from Preview Public Deck.

screen shot 2017-03-19 at 2 49 02 am

### PR DESCRIPTION
**Pull request by Tyler-Brenneman**
Closes #123

### CODE REVIEW

File: Cue/app/tabs/library/CardListView.js [hunk 1]
```diff
@@ -13,6 +13,7 @@ import ListViewHairlineSeparator from '../../common/ListViewHairlineSeparator'
 type Props = {
   cards: Array<Card>,
   isFiltering: boolean,
+  accession: ?string,
```
Comment (mattyu007) [inline Cue/app/tabs/library/CardListView.js]: This actually needs to be `accession?: string` for Flow to type-check this correctly since the `accession` prop itself might be completely missing, rather than the prop occasionally having a `null` value.

**Review by mattyu007 — APPROVED** [review]
Other than the type thing, looks good.
